### ISSUE TITLE
Buffer overrun win run_xdp when formatting threadname

### ISSUE THREAD

**Issue by ahlabenadam** [driesdewinter/rtptest#1]
run_xdp functions format _threadname_ based on device name. In the case when device name is long, it will overrun the buffer.
On my setup relevant device is named '_enp134f0s0np0_' thus concatenation of "rtprx:" and the name produces a string with length 19 that is larger then _threadname._

**Comment by driesdewinter** [comment]
Oops, fixed by aacd3d1dbcf10d0559f2b4dd48d46448efa00962
